import Head from 'next/head';
import Image from 'next/image';
import { Geist, Geist_Mono } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import UnderlinedText from '@/components/UnderlinedText';
import Card from '@/components/Card';
import IntroSection from '@/components/IntroSection';
import ScreenSection from '@/components/ScreenSection';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>uteach</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div
        className={`${styles.container} ${geistSans.variable} ${geistMono.variable}`}
      >
        <Navbar />
        <main className={styles.contentContainer}>
          <IntroSection />

          <ScreenSection />

          {/* testimonials */}
          <section className={`${styles.section} ${styles.sectionTestimonial}`}>
            <div className={styles.testimonial}>
              <svg
                width='48'
                height='48'
                viewBox='0 0 48 48'
                fill='none'
                xmlns='http://www.w3.org/2000/svg'
                className={styles.testimonialArrow}
              >
                <path
                  fillRule='evenodd'
                  clipRule='evenodd'
                  d='M32.341 8.90901C33.2197 9.78769 33.2197 11.2123 32.341 12.091L20.432 24L32.341 35.909C33.2197 36.7877 33.2197 38.2123 32.341 39.091C31.4623 39.9697 30.0377 39.9697 29.159 39.091L15.659 25.591C14.7803 24.7123 14.7803 23.2877 15.659 22.409L29.159 8.90901C30.0377 8.03033 31.4623 8.03033 32.341 8.90901Z'
                  fill='white'
                />
              </svg>

              <div className={styles.testimonialTextContainer}>
                <p className={styles.sectionText}>
                  Id urna, nisl, ut quam. Diam suspendisse fringilla quam arcu
                  mattis est velit in. Nibh in purus sit convallis phasellus ut.
                  At vel erat ultricies commodo. Neque suspendisse a habitasse
                  commodo.
                </p>
                <p className={styles.sectionText}>
                  Marie Poirot,
                  <span className={styles.testimonialAuthor}>Bigapp</span>
                </p>
                <div className={styles.testimonialPipsContainer}>
                  <span
                    className={`${styles.testimonialPip} ${styles.testimonialPipSelected}`}
                  ></span>
                  <span className={styles.testimonialPip}></span>
                  <span className={styles.testimonialPip}></span>
                  <span className={styles.testimonialPip}></span>
                  <span className={styles.testimonialPip}></span>
                </div>
              </div>

              <div className={styles.testimonialImageContainer}>
                <Image
                  src='/assets/testimonial.webp'
                  alt='testimonial author'
                  fill
                  sizes='(max-width: 875px) 125px, 100%'
                  style={{ objectFit: 'contain' }}
                />
                <Image
                  src='/assets/decoration.webp'
                  alt='testimonial decoration'
                  width={155}
                  height={155}
                  className={styles.testimonalDecoration}
                />
              </div>

              <svg
                width='48'
                height='48'
                viewBox='0 0 48 48'
                fill='none'
                xmlns='http://www.w3.org/2000/svg'
                className={styles.testimonialArrow}
              >
                <path
                  fillRule='evenodd'
                  clipRule='evenodd'
                  d='M15.659 8.90901C16.5377 8.03033 17.9623 8.03033 18.841 8.90901L32.341 22.409C33.2197 23.2877 33.2197 24.7123 32.341 25.591L18.841 39.091C17.9623 39.9697 16.5377 39.9697 15.659 39.091C14.7803 38.2123 14.7803 36.7877 15.659 35.909L27.568 24L15.659 12.091C14.7803 11.2123 14.7803 9.78769 15.659 8.90901Z'
                  fill='#0F172A'
                />
              </svg>
            </div>
          </section>
        </main>
        <Footer />
      </div>
    </>
  );
}
